kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jumper-wechat
  namespace: jumper  #命名空间
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
# jumper-wechat 容器
apiVersion: apps/v1  #版本号
kind: Deployment   #创建的资源类型
metadata:   #该资源的元数据，name必选项
  name: jumper-wechat   #name描述
  namespace: jumper  #命名空间
spec:    #规格说明
  replicas: 1    #副本数量
  selector:
    matchLabels:
      app: jumper-wechat
  template:      #定义pod的模板，配置文件的重要部分
    metadata:     #定义pod的元数据，至少定义一个label
      labels:
        app: jumper-wechat   #该pod拥有的标签，对应上面的spec.selector.matchLabels.app，否则匹配不上
    spec:        #描述pod的规格，定义pod中每个容器的属性，name和image必须
      imagePullSecrets:
      - name: hwhubsecret
      containers:    #容器描述
      - name: jumper-wechat
        image: swr.cn-south-1.myhuaweicloud.com/jumper/jumper-wechat-uat:latest        #镜像来源名字
        resources:
          requests:
            memory: "512Mi"
            cpu: "100m"          
        imagePullPolicy: Always     #拉取策略
        ports:   # 容器公开的端口列表。在这里公开端口可以为系统提供关于容器使用的网络连接的额外信息，但主要是提供描述信息
        - name: jumper-wechat
          containerPort: 6003
        env:
        - name: NACOS_ADDRESS  
          value: "nacos-headless.jumper:8848"            
        - name: SENTINEL_ADDRESS  
          value: "sentinel-service.jumper:8858"           
        - name: TZ  
          value: "Asia/Shanghai"            
        volumeMounts:
        - name: jumper-wechat-data   # volumeClaimTemplates的名称
          mountPath: /logs/jumper-wechat     # 需要挂载的容器内地址
          subPath: ./logs     # 挂载的存储卷路径（必须是相对路径）     
        - name: jumper-wechat-data   # volumeClaimTemplates的名称
          mountPath: /opt/verify     # 需要挂载的容器内地址
          subPath: ./verify     # 挂载的存储卷路径（必须是相对路径）               
      volumes:
      - name: jumper-wechat-data
        persistentVolumeClaim:
          claimName: jumper-wechat
            
---
# 内部访问的Headless Service无头服务
apiVersion: v1
kind: Service
metadata:
  name: jumper-wechat-service
  namespace: jumper  #命名空间  
spec:
  selector:
    app: jumper-wechat
  ports:
  - name: jumper-wechat
    port: 6003
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "True"
  name: jumper-wechat-ingress
  namespace: jumper  #命名空间
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - mini-wechat.ghosttyq.site
    secretName: mini-wechat.ghosttyq.site
  rules:  # 用于定义当前Ingress资源的转发规则列表；由rules定义规则，或没有匹配到规则时，所有的流量会转发到由backend定义的默认后端
  - host: mini-wechat.ghosttyq.site
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:  #  默认的后端用于服务那些没有匹配到任何规则的请求；定义Ingress资源时，必须要定义backend或rules两者之一，该字段用于让负载均衡器指定一个全局默认的后端
          service:
            name: jumper-wechat-service    # Service资源名称
            port: 
              number: 6003   #Service端口（可以取ports里面的name，也可以取数字端口）        
