---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: rocketmq
  name: configmap-rocketmq-console-ng
data:
  JAVA_OPTS: "-Drocketmq.namesrv.addr=service-rocketmq-namesrv.rocketmq.svc.cluster.local:9876; -Dcom.rocketmq.sendMessageWithVIPChannel=false"
---
kind: Service
apiVersion: v1
metadata:
  namespace: rocketmq
  name: service-rocketmq-console-ng
  labels:
    app: service-rocketmq-console-ng
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30880   #  外部机器可访问的端口
  selector:
    app: pod-rocketmq-console-ng
  type: NodePort    

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: rocketmq
  name: deployment-rocketmq-console-ng
  labels:
    app: deployment-rocketmq-console-ng
spec:
  # 1 个实例
  replicas: 1
  selector:
    matchLabels:
      app: pod-rocketmq-console-ng
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-console-ng
    spec:
      imagePullSecrets:
      - name: hwhubsecret
      containers:
      - image: swr.cn-south-1.myhuaweicloud.com/ghosttyq/rocketmq-console-ng:latest
        securityContext:
          privileged: true
        imagePullPolicy: Always
        name: container-rocketmq-console-ng
        ports:
        - protocol: TCP
          containerPort: 8080

        # 挂载configmap-apollo-portal-server相关配置
        envFrom:
        - configMapRef:
            name: configmap-rocketmq-console-ng
        # 计算资源分配
        resources:
          # 初始请求资源
          requests:
            cpu: 0.5
            memory: 512Mi
          # 资源限制
          limits:
            cpu: 0.5
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 8080
          # 120s 内, server 未启动则重启 container
          initialDelaySeconds: 120
          periodSeconds: 15
      restartPolicy: Always

---
#ingress
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: rocketmq-console-ingress
#  namespace: rocketmq
#spec:
#  rules:
#  - host: mq-console.sddk.com
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: service-rocketmq-console-ng-prod
#            port:
#              number: 8080

