apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  namespace: redis  #命名空间
  labels:
    app: redis-ha
    release: redis
spec:
  selector:
    app: redis-ha
    statefulset.kubernetes.io/pod-name: redis-redis-ha-server-0
  ports:
  - name: server
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: sentinel
  clusterIP: None
